### ISSUE TITLE
"ng serve" failed

### ISSUE THREAD

**Issue by muthahir-nawaz** [madoar/angular-archwizard#136]
Your global Angular CLI version (6.0.8) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-07-24T10:09:37.704Z
Hash: 27c93922099d4673c048
Time: 16653ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 455 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 605 kB [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 163 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 153 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 9.47 MB [initial] [rendered]

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/bootstrap/dist/css/bootstrap.min.
css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at D:\angular-archwizard-demo-master\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (D:\angular-archwizard-demo-master\node_modules\browserslist\index.js:132:18)
    at browserslist (D:\angular-archwizard-demo-master\node_modules\browserslist\index.js:224:16)
    at Browsers.parse (D:\angular-archwizard-demo-master\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (D:\angular-archwizard-demo-master\node_modules\autoprefixer\lib\browsers.js:52:30)
    at loadPrefixes (D:\angular-archwizard-demo-master\node_modules\autoprefixer\lib\autoprefixer.js:70:24)
    at plugin (D:\angular-archwizard-demo-master\node_modules\autoprefixer\lib\autoprefixer.js:81:24)
    at LazyResult.run (D:\angular-archwizard-demo-master\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (D:\angular-archwizard-demo-master\node_modules\postcss\lib\lazy-result.js:192:32)
    at D:\angular-archwizard-demo-master\node_modules\postcss\lib\lazy-result.js:197:27
    at <anonymous>

webpack: Failed to compile.

is it because angular cli version mismatch?

**Comment by muthahir-nawaz** [comment]
sorry, wrong window
