### ISSUE TITLE
angular 10 update causes failing unit test

### ISSUE THREAD

**Issue by nadflores** [madoar/angular-archwizard#332]
An error was thrown in afterAll
  Unhandled promise rejection: TypeError: Cannot read property 'exit' of null
  TypeError: Cannot read property 'exit' of null
      at http://localhost:9876/_karma_webpack_/node_modules/angular-archwizard/fesm2015/angular-archwizard.js:549:1
      at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
      at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
      at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
      at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
      at http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:857:1
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:399:1)
      at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:323:1)
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:398:1)
      at Zone.runTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:167:1)

**Comment by madoar** [comment]
Can you please provide some more information?
Which version of npm are you using?
Which test(s) are failing?
What do you mean by "Angular 10 update causes failing unit test"?
Is it a test in your application or in `angular-archwizard`?

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
